apiVersion: v1
kind: ConfigMap
metadata:
  name: stakater-nordmart-inventory-postgresql-config.yaml
  labels:
    app: postgres
data:
  POSTGRES_DB: inventory
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password