---
# Source: application/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: inventory
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.13"
    release: "NAMESPACE_NAME-inventory"
    heritage: "Tiller"
  name: inventory-postgresql-secret
data:
  POSTGRESQL_PASSWORD: cGFzc3dvcmQ=
---