---
# Source: application/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: inventory
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.13"
    release: "NAMESPACE_NAME-inventory"
    heritage: "Tiller"
  name: inventory